
public enum Fakultaet {
	BIOECHNOLOGIE, 
	ELEKTROTECHNIK, 
	GESTALTUNG, 
	INFORMATIK, 
	INFORMATIONSTECHNIK, 
	MASCHINENBAU, 
	SOZIALWESEN, 
	VERFAHRENS_UND_CHEMIETECHNIK, 
	WIRTSCHAFTSINGENIEURSWESEN;
}
