
public enum Studiengang {
	UNTERNEHMENS_UND_WIRTSCHAFSTINFORMATIK, 
	MASCHINENBAU, 
	INFORMATIK, 
	MEDIZINISCHE_INFORMATIK, 
	TRANSLATION_STUDIES_FOR_IT, 
	BIOLOGISCHE_CHEMIE, 
	DOZENTEN_NOTFALL_LÖSUNG;
}
